### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by ghost** [AngelDE98/FEZMod#29]
Logos and title screen appear as normal, but after hitting Enter/A the game crashes.

**Comment by ghost** [comment]
I have a similar problem to the one on thread https://github.com/0x0ade/FEZMod/issues/16 .

However, now the game just instantly crashes. No logos, no screen, nothing.

**Comment by ghost** [comment]
After installing nightly build 300, the game strangely works. Unfortunately, it lags a lot, but that's probably because I'm running it on a toaster. XP

**Comment by 0x0ade** [comment]
Sorry for the late answer - I've had problems with my laptop. (CPU's hot, at least not overheating anymore.)

The stable builds are quite outdated and I haven't worked on FEZMod for quite some time. I'm currently considering to drop features and release a stable that way. Unfortunately I probably won't touch FEZMod for quite some time (final exams; lost motivation).

Also, [FEZMod.Installer](https://www.dropbox.com/s/21t3w3vtthrlxca/FEZMod.Installer.exe?dl=0) is a thing. Make sure to "fix files" via Steam if FEZMod is already installed.

FEZMod's quite unoptimized. Optimization is even one of the last few things I did before pausing progress. What GPU are you using? How much does the FPS drop? (Use any FPS counter of your choice or the one in the Steam overlay.)

**Comment by discohsmiley888** [comment]
Not sure if you saw it or not, but I got the mod working. I tried out nightly build 300 via the installer and the game was able to run. Sorry about that!

**Comment by ghost** [comment]
I know about the installer. That's really what got the game working in the first place.

As for the lag, in case your curious, the game dropped from about 30 FPS to around or under 10 FPS.  I'm running on a pretty bad machine, so I'm quite used to lag. Personally, I'm not too worried about it.

**Comment by 0x0ade** [comment]
Yeah, I saw that you're using build 300.

The FPS drop doesn't just happen on your PC - it seems to be an issue in
FEZMod, but I don't know what part of it should be blamed yet. And as
working on FEZMod is hard for me during my final exams and until I get it
running properly on Android (it's running, but glitched; my PC recently
shuts down as it overheats to 115°C), this repo will stay kinda silent... :/

discohsmiley888 notifications@github.com schrieb am Sa., 16. Apr. 2016
03:15:

**Comment by 0x0ade** [comment]
I've noticed that FEZMod for FEZ 1.11 was logging a single, useless line quite often. Could you please check if the FPS issue still exists with the newest devbuild (306)?

**Comment by ghost** [comment]
I can't seem to be able to install the new build. The installer shows this message some time into the installation:

Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'MonoMod, Version=0.0.4.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.MetadataResolver.Resolve(MethodReference method)
   at Mono.Cecil.ModuleDefinition.Resolve(MethodReference method)
   at Mono.Cecil.MethodReference.Resolve()
   at MonoMod.MonoMod.FindLinked(MethodReference method)
   at MonoMod.MonoMod.PatchRefsInMethod(MethodDefinition method)
   at MonoMod.MonoMod.PatchRefs()
   at MonoMod.MonoMod.AutoPatch(Boolean read, Boolean write)
   at FezGame.Mod.Installer.FezModder.Mod(InstallerWindow ins)

**Comment by 0x0ade** [comment]
That's weird as I can't replicate it and another person also can't replicate it. Could you please share your complete log?

**Comment by ghost** [comment]
FEZMod Installer v16.1.5.0
FEZ 1.11
No previous FEZMod installation found.
Still reverting to non-FEZMod backup...
Reverting: Common.dll
Reverting: EasyStorage.dll
Reverting: FEZ.exe
Reverting: FezEngine.dll
Reverting: MonoGame.Framework.dll
Reloading FEZ.exe
Backing up: Common.dll
Backing up: EasyStorage.dll
Backing up: MonoGame.Framework.dll
Backing up: FezEngine.dll
Backing up: FEZ.exe
FEZMod Nightly 308
Downloading http://fezmod.xyz/files/travis/jafm/308/JAFM-DEV.zip...
Download complete, 6026.67 KiB in 8.32 s.
Checking for FEZMOD/...
Entry: InstallerVersion.txt: 7 bytes
Found version file.
Entry: FEZMOD/: 0 bytes
Entry: FEZMOD/Common.Mod.mm.dll: 4096 bytes
Entry: FEZMOD/EasyStorage.Mod.mm.dll: 3584 bytes
Entry: FEZMOD/FEZ.Editor.mm.dll: 84480 bytes
Entry: FEZMOD/FezEngine.Mod.mm.dll: 121856 bytes
Entry: FEZMOD/FEZ.Mod.mm.dll: 152576 bytes
Entry: FEZMOD/FEZ.Speedrun.mm.dll: 43520 bytes
Entry: FEZMOD/MonoGame.Framework.FML.mm.dll: 5120 bytes
Entry: FEZMOD/Common.Mod.mm.dll.mdb: 889 bytes
Entry: FEZMOD/EasyStorage.Mod.mm.dll.mdb: 569 bytes
Entry: FEZMOD/FEZ.Editor.mm.dll.mdb: 24696 bytes
Entry: FEZMOD/FezEngine.Mod.mm.dll.mdb: 58604 bytes
Entry: FEZMOD/FEZ.Mod.mm.dll.mdb: 43813 bytes
Entry: FEZMOD/FEZ.Speedrun.mm.dll.mdb: 16541 bytes
Entry: FEZMOD/MonoGame.Framework.FML.mm.dll.mdb: 1153 bytes
Entry: FEZMOD-FNA/: 0 bytes
Entry: FEZMOD-FNA/Common.Mod.mm.dll: 4608 bytes
Entry: FEZMOD-FNA/EasyStorage.Mod.mm.dll: 4096 bytes
Entry: FEZMOD-FNA/FEZ.Editor.mm.dll: 84480 bytes
Entry: FEZMOD-FNA/FezEngine.Mod.mm.dll: 121344 bytes
Entry: FEZMOD-FNA/FEZ.Mod.mm.dll: 152064 bytes
Entry: FEZMOD-FNA/FEZ.Speedrun.mm.dll: 43520 bytes
Entry: FEZMOD-FNA/MonoGame.Framework.FML.mm.dll: 5120 bytes
Entry: FEZMOD-FNA/Common.Mod.mm.dll.mdb: 1087 bytes
Entry: FEZMOD-FNA/EasyStorage.Mod.mm.dll.mdb: 671 bytes
Entry: FEZMOD-FNA/FEZ.Editor.mm.dll.mdb: 24690 bytes
Entry: FEZMOD-FNA/FezEngine.Mod.mm.dll.mdb: 58485 bytes
Entry: FEZMOD-FNA/FEZ.Mod.mm.dll.mdb: 43546 bytes
Entry: FEZMOD-FNA/FEZ.Speedrun.mm.dll.mdb: 16547 bytes
Entry: FEZMOD-FNA/MonoGame.Framework.FML.mm.dll.mdb: 1159 bytes
Entry: FEZMOD/LIBS/: 0 bytes
Entry: FEZMOD-FNA/LIBS/: 0 bytes
Entry: FEZMOD-FNA/LIBS/win32/: 0 bytes
Entry: FEZMOD-FNA/LIBS/win32/libjpeg-9.dll: 223232 bytes
Entry: FEZMOD-FNA/LIBS/win32/zlib1.dll: 123904 bytes
Entry: FEZMOD-FNA/LIBS/win32/libvorbisfile.dll: 29184 bytes
Entry: FEZMOD-FNA/LIBS/win32/libtheora.dll: 174080 bytes
Entry: FEZMOD-FNA/LIBS/win32/MojoShader.dll: 118784 bytes
Entry: FEZMOD-FNA/LIBS/win32/libpng16-16.dll: 200704 bytes
Entry: FEZMOD-FNA/LIBS/win32/SDL2.dll: 779776 bytes
Entry: FEZMOD-FNA/LIBS/win32/libtheoraplay.dll: 15360 bytes
Entry: FEZMOD-FNA/LIBS/win32/SDL2_image.dll: 93184 bytes
Entry: FEZMOD-FNA/LIBS/win32/libogg.dll: 17920 bytes
Entry: FEZMOD-FNA/LIBS/win32/libvorbis.dll: 1624576 bytes
Entry: FEZMOD-FNA/LIBS/win32/soft_oal.dll: 843809 bytes
Entry: FEZMOD-FNA/LIBS/lib/: 0 bytes
Entry: FEZMOD-FNA/LIBS/lib/libtheoraplay.so: 22684 bytes
Entry: FEZMOD-FNA/LIBS/lib/libogg.so.0: 26032 bytes
Entry: FEZMOD-FNA/LIBS/lib/libSDL2_image-2.0.so.0: 76258 bytes
Entry: FEZMOD-FNA/LIBS/lib/libjpeg.so.62: 290032 bytes
Entry: FEZMOD-FNA/LIBS/lib/libopenal.so.1: 622605 bytes
Entry: FEZMOD-FNA/LIBS/lib/libmojoshader.so: 187497 bytes
Entry: FEZMOD-FNA/LIBS/lib/libvorbis.so.0: 179408 bytes
Entry: FEZMOD-FNA/LIBS/lib/libtheoradec.so.1: 67032 bytes
Entry: FEZMOD-FNA/LIBS/lib/libvorbisfile.so.3: 35964 bytes
Entry: FEZMOD-FNA/LIBS/lib/libSDL2-2.0.so.0: 1377605 bytes
Entry: FEZMOD-FNA/LIBS/lib/libpng15.so.15: 183712 bytes
Entry: FEZMOD-FNA/LIBS/lib64/: 0 bytes
Entry: FEZMOD-FNA/LIBS/lib64/libvorbis.so.0: 182952 bytes
Entry: FEZMOD-FNA/LIBS/lib64/libvorbisfile.so.3: 35256 bytes
Entry: FEZMOD-FNA/LIBS/lib64/libSDL2_image-2.0.so.0: 78054 bytes
Entry: FEZMOD-FNA/LIBS/lib64/libtheoraplay.so: 25362 bytes
Entry: FEZMOD-FNA/LIBS/lib64/libpng15.so.15: 170976 bytes
Entry: FEZMOD-FNA/LIBS/lib64/libmojoshader.so: 193285 bytes
Entry: FEZMOD-FNA/LIBS/lib64/libtheoradec.so.1: 66152 bytes
Entry: FEZMOD-FNA/LIBS/lib64/libjpeg.so.62: 260664 bytes
Entry: FEZMOD-FNA/LIBS/lib64/libogg.so.0: 26800 bytes
Entry: FEZMOD-FNA/LIBS/lib64/libSDL2-2.0.so.0: 1348738 bytes
Entry: FEZMOD-FNA/LIBS/lib64/libopenal.so.1: 634399 bytes
Entry: FEZMOD-FNA/LIBS/osx/: 0 bytes
Entry: FEZMOD-FNA/LIBS/osx/libopenal.1.dylib: 1056448 bytes
Entry: FEZMOD-FNA/LIBS/osx/libtheoradec.1.dylib: 145948 bytes
Entry: FEZMOD-FNA/LIBS/osx/libogg.0.dylib: 62584 bytes
Entry: FEZMOD-FNA/LIBS/osx/libtheoraplay.dylib: 66164 bytes
Entry: FEZMOD-FNA/LIBS/osx/libvorbis.0.dylib: 389868 bytes
Entry: FEZMOD-FNA/LIBS/osx/libSDL2_image-2.0.0.dylib: 148368 bytes
Entry: FEZMOD-FNA/LIBS/osx/libSDL2-2.0.0.dylib: 2143448 bytes
Entry: FEZMOD-FNA/LIBS/osx/libvorbisfile.3.dylib: 88120 bytes
Entry: FEZMOD-FNA/LIBS/osx/libmojoshader.dylib: 397104 bytes
FEZMOD/ found.
Extracting: FEZMOD/Common.Mod.mm.dll -> C:\Program Files (x86)\Steam\SteamApps\common\FEZ\Common.Mod.mm.dll
Extracting: FEZMOD/EasyStorage.Mod.mm.dll -> C:\Program Files (x86)\Steam\SteamApps\common\FEZ\EasyStorage.Mod.mm.dll
Extracting: FEZMOD/FEZ.Editor.mm.dll -> C:\Program Files (x86)\Steam\SteamApps\common\FEZ\FEZ.Editor.mm.dll
Extracting: FEZMOD/FezEngine.Mod.mm.dll -> C:\Program Files (x86)\Steam\SteamApps\common\FEZ\FezEngine.Mod.mm.dll
Extracting: FEZMOD/FEZ.Mod.mm.dll -> C:\Program Files (x86)\Steam\SteamApps\common\FEZ\FEZ.Mod.mm.dll
Extracting: FEZMOD/FEZ.Speedrun.mm.dll -> C:\Program Files (x86)\Steam\SteamApps\common\FEZ\FEZ.Speedrun.mm.dll
Extracting: FEZMOD/MonoGame.Framework.FML.mm.dll -> C:\Program Files (x86)\Steam\SteamApps\common\FEZ\MonoGame.Framework.FML.mm.dll
Extracting: FEZMOD/Common.Mod.mm.dll.mdb -> C:\Program Files (x86)\Steam\SteamApps\common\FEZ\Common.Mod.mm.dll.mdb
Extracting: FEZMOD/EasyStorage.Mod.mm.dll.mdb -> C:\Program Files (x86)\Steam\SteamApps\common\FEZ\EasyStorage.Mod.mm.dll.mdb
Extracting: FEZMOD/FEZ.Editor.mm.dll.mdb -> C:\Program Files (x86)\Steam\SteamApps\common\FEZ\FEZ.Editor.mm.dll.mdb
Extracting: FEZMOD/FezEngine.Mod.mm.dll.mdb -> C:\Program Files (x86)\Steam\SteamApps\common\FEZ\FezEngine.Mod.mm.dll.mdb
Extracting: FEZMOD/FEZ.Mod.mm.dll.mdb -> C:\Program Files (x86)\Steam\SteamApps\common\FEZ\FEZ.Mod.mm.dll.mdb
Extracting: FEZMOD/FEZ.Speedrun.mm.dll.mdb -> C:\Program Files (x86)\Steam\SteamApps\common\FEZ\FEZ.Speedrun.mm.dll.mdb
Extracting: FEZMOD/MonoGame.Framework.FML.mm.dll.mdb -> C:\Program Files (x86)\Steam\SteamApps\common\FEZ\MonoGame.Framework.FML.mm.dll.mdb

Now comes the real "modding" / patching process.
If the installer were to output all the MonoMod stuff here,
the installer would slow down and maybe consume more RAM
than 65 open tabs in Chrome. :/
It may seem like the Installer may be stuck sometimes. Go make
yourself a coffee in the meantime - it doesn't get stuck.
It may _crash_, though - and in this case, debug stuff appears
here. Please put that debug stuff onto http://hastebin.com/ and
send it to @0x0ade on Twitter or FEZMod on GitHub.

Modding Common.dll
Common.dll is not that huge - not much to say here.

Modding EasyStorage.dll
EasyStorage.dll also isn't huge - most probably Steam and Android stuff.

Modding MonoGame.Framework.dll
Wait... where's FNA? Well, I guess you're using old FEZ.

Modding FezEngine.dll
This may take some time as the Trixel Engine also becomes the
"FEZMod Engine." If something low-level happens, for example
loading textures & music, handling geometry, ... it's here.
And every FEZ mod needs to use the "FEZMod Engine" to register
itself as mod to the FEZMod core. If it's complicated, don't worry:
This message simply means that modding FezEngine.dll takes time.

Modding FEZ.exe
Remember how long FezEngine.dll was? That was nothing!
Now it's time to get yourself some coffee.
It'd be nice to give you more exact progress here,
but as said before, it would kill the installer.
You won't see anything happening here, but don't panic:
If the installer crashes, an error log appears here.

Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'MonoMod, Version=0.0.4.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.MetadataResolver.Resolve(MethodReference method)
   at Mono.Cecil.ModuleDefinition.Resolve(MethodReference method)
   at Mono.Cecil.MethodReference.Resolve()
   at MonoMod.MonoMod.FindLinked(MethodReference method)
   at MonoMod.MonoMod.PatchRefsInMethod(MethodDefinition method)
   at MonoMod.MonoMod.PatchRefs()
   at MonoMod.MonoMod.AutoPatch(Boolean read, Boolean write)
   at FezGame.Mod.Installer.FezModder.Mod(InstallerWindow ins)

This time around I tried to install build 308, but it's the same as with build 306.
